### ISSUE TITLE
Just can't get REX-Ray working with this!

### ISSUE THREAD

**Issue by mcmast2** [emccode/puppet-scaleio#8]
Hi,
I've been trying to get this script working to the way it's supposed to for over two weeks now (don't laugh, please) with little success. Initially it was things like vagrant missing the correct plugins and certificate errors blocking files from being downloaded, but now that I've jumped those hurdles problems with REX-Ray are starting to pop up. When I ssh into mdm1 and try running REX-Ray CLIs, two distinct things will come out of it:
- Any rexray input will have mdm1 just hang until it complains about "fatal runtime error: out of memory"
- The CLIs will work but they don't work as expected. "rexray help" works fine, but "rexray get-instance" returns nothing and "rexray new-volume" shows all the inputs as being null (i.e. size=0, name = "", etc) and doesn't actually create a volume.

I'm certain I've followed the instructions to a T, so I don't know what could be wrong. Have you experienced these issues before?

**Comment by clintonskitson** [comment]
Can you paste the ```REXRAY_DEBUG=true rexray get-instance``` output here?  Are you sure that the ScaleIO instance is functioning?  In most cases where this doesn't work as expected it has to do with memory requirements not being met which overall results in the SIO gateway not working as expected.

**Comment by mcmast2** [comment]
![image](https://cloud.githubusercontent.com/assets/12936721/8831507/ca270414-3070-11e5-97ed-4fc8fbdcde01.png)
Here's the error I'm getting. I believe the ScaleIO instance is functioning, since scli commands are working fine - I can log in, check the volumes, that sort of thing.

**Comment by clintonskitson** [comment]
During the discovery phase of ScaleIO, there is an error reported as "systemid or systemname not found".  Check your GOSCALEIO_SYSTEMNAME or GOSCALEIO_SYSTEMID env variable to ensure it is valid.

**Comment by kacole2** [comment]
@mcmast2 try this
```sudo bash
systemctl restart rexray
REXRAY_DEBUG=true rexray get-instance
```

**Comment by mcmast2** [comment]
Thanks for the tips guys. There's no GOSCALEIO_SYSTEMNAME/SYSTEMID, and I think I've identified the problem - here's a big error report I get when building the VMs with "vagrant up":

![image](https://cloud.githubusercontent.com/assets/12936721/8877272/82ccfa00-31f2-11e5-9332-7f6f61683112.png)

Seems like it has a coronary and times out when it tries to run the command to switch to cluster mode, and that makes the ScaleIO cluster not function properly (or at all) because it's missing the right dependencies. I'm poking through the Vagrantfile to try and give it more time before it times out but I'm not finding anything like that. Any advice at this point?

**Comment by kacole2** [comment]
@mcmast2 I've felt your frustration. Here's what I did so could demo REXray. 

git clone https://github.com/clintonskitson/vagrant-scaleio
cd vagrant-scaleio
git checkout rexray_updates
vagrant up

I took atleast 2-3 tries for it to come up correctly in my Mac with 8gb. 

After that, the directions for using rexray for a demo of showing persistent data stores are found in a different repo. 
https://github.com/emccode/vagrant-puppet-scaleio/tree/docker_1.7rc3_experimental_rexray

Sorry about all that. Once @clintonskitson is back from vacation it will get cleaned up

**Comment by mcmast2** [comment]
Thanks very much - after some fair amount of trial and error I got it working, just like you said. Can't wait to see the whole thing get cleaned up. Case closed!

**Comment by kacole2** [comment]
great. FYI, if you shut it down, let the VMs go to sleep or whatever, it
breaks. :(

Kenny

**Comment by mcmast2** [comment]
Actually, I've tried it twice after restarting my computer both times and it worked fine both times! I have no idea what the difference is but I figured I'd mention that

**Comment by kacole2** [comment]
how much RAM do you have running on your system?

**Comment by mcmast2** [comment]
6 gigs. It's Windows 7, if that helps.

**Comment by kacole2** [comment]
thanks. everyone on our team has 8GB or more and things seem to really get sluggish on 8GB

**Comment by mcmast2** [comment]
It's also worth noting that I halved the size of each virtual machine's RAM by editing the Vagrantfile so that they'd work on my machine. If it's so sluggish then that seems like a valid option
